### ISSUE TITLE
Enquiry on Azure Cache For Redis AOF

### ISSUE THREAD

**Issue by SQLConjuror** [mdrakiburrahman/rakirahman.me#10]
Hi Raki Rahman,

Good Day! I just read your awesome blog post about Azure cache for Redis. 

I would just to ask a question regarding AOF data persistence.

I'm tasked to test AOF data restoration. I understand that AOF restoration on the same Redis is done automatically with AOF data persistence configuration during server restart. 

- How can we simulate a data loss scenario in Azure cache for Redis, then perform the AOF data restoration? 
     I tried to Reboot both master and replica at the same time, but I observe that the reboot happens one server at a time when I saw 
      2 consecutive failover alerts occurrence. I also tried rebooting 2 servers at the same time without enabling AOF data persistence 
       but I also notice no data loss.

- Can we setup an Azure cache for Redis without a Replica so that when I reboot, data will surely be loss, and we can then simulate AOF recovery. 

thank you. 

Best regards, 
Ricky

**Comment by mdrakiburrahman** [comment]
Hey Ricky, thanks for reaching out, apologies for the super late reply as I haven't been monitoring this as well as I should. 

Tbh I am not sure if being a managed service, Azure would let you run scenarios that deliberately force data loss, as from Azure's perspective "all Caches are Prod Caches" - e.g. Azure doesn't know that this is Ricky's "Sandbox" cache - it could be a mission critical one. 

I'm sure you've read through this, but if not - this explains at a high level how the failover occurs; https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-failover#what-is-a-failover

If you truly do need these back-end details, I'd recommend if you can open up a support ticket and request to get in touch with Redis Product Group to get your answers, our Support personnel have an asynchronous channel to communicate questions like this to the Product Team. 

Hope that sort of helps!
