### ISSUE TITLE
Unable to view Alawys-on Availability Group folder in Azure Arc SQL MI

### ISSUE THREAD

**Issue by Syed-IN** [mdrakiburrahman/rakirahman.me#19]
Hi Rakirahman,

Good Day!!

I'm writing to you with a hope that I could fix my issue with your technical advice on Azure Stack HCI with Arc SQL MI deployment.

Issue Description:

I have Azure Stack HCI deployed with AKS cluster and on top of that Arc SQL MI. I'm a SQL DBA and i'm not sure about AKS configurations, I have been asked to deploy SQL MI and using Azure portal I have deployed and it was successful with 3 replicas. All good until here, the problem starts when I connect Arc SQL MI using SSMS i'm unable to see Availability Group folder at Instance level.

I did queried sys.dmvs to check replicas, AG Groups and listener, all configs are good except the listener IP which shows 0.0.0.0 in the output. 

I'm reading multiple docs but unable to get proper document to fix the issue. I suspect i'm I missing any configuration when deploying ARC MI ? OR do i need to specify special parameter at AKS end ?

Any help will be much appreciated. I need to submit this project by this week. Kindly help... please help.

Regards,
Syed Umar Kashif.

**Comment by mdrakiburrahman** [comment]
@Syed-IN which version of SSMS are you running? Is it possible to share screenshots of the behavior you described via words?

For example - SSMS version
![image](https://user-images.githubusercontent.com/46581776/230590973-3553a499-f061-484b-9d94-d17817f757e9.png)

For example - here's a 2 replica Arc SQL MI on my K8s cluster, SSMS working fine:
![image](https://user-images.githubusercontent.com/46581776/230591266-3bf18567-8df1-4658-a057-3b7d0cd42565.png)

**Comment by Syed-IN** [comment]
Hi Raki,

I was able to overcome the issue by using an older version of SSMS. I need
your help to deploy DAG, could you please help me with the scripts or any
document used by you.

Regards,
Syed.

**Comment by mdrakiburrahman** [comment]
Please see notes here:
https://github.com/mdrakiburrahman/sql-miaa-migrations#miaa-migration-setup

**Comment by Syed-IN** [comment]
Assalamuallikum,

Brother, I need your help to get the possibilities to migrate on-premise
SQL server to Azure Arc SQL MI. What would be the best choice with minimal
downtime ?
 Logshipping -- I guess this won't work with MI.
 Always-on
Distributed Availability Group.

If you have any references please let me know, I will go through it.

Apart from the above is there any other technique to perform db migration?

Regards,
Syed Umar Kashif.
